[options]
library = "Gjs"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."
girs_directories = ["./gir-files", "."]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

external_libraries = [
    "GLib",
    "Gio",
    "GObject",
]

generate = [
  "Gjs.Error",
  "Gjs.JSError",
  "Gjs.*",
]

manual = [
  "GLib.Error",
  "Gio.File"
]

[[object]]
name = "Gjs.Context"
status = "generate"
generate_builder = true
  [[object.function]]
  name = "get_native_context"
  ignore = true # manual

[[object]]
name = "Gjs.Coverage"
status = "generate"
generate_builder = true

[[object]]
name = "Gjs.Profiler"
status = "generate"
  [[object.function]]
  name = "set_capture_writer"
  ignore = true # manual
  [[object.function]]
  name = "chain_signal"
  ignore = true # manual
