// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

#[doc(alias = "gjs_dumpstack")]
pub fn dumpstack() {
    assert_initialized_main_thread!();
    unsafe {
        ffi::gjs_dumpstack();
    }
}

/// Returns the underlying version of the JS engine.
///
/// # Returns
///
/// a string
#[doc(alias = "gjs_get_js_version")]
#[doc(alias = "get_js_version")]
pub fn js_version() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::gjs_get_js_version()) }
}

#[doc(alias = "gjs_memory_report")]
pub fn memory_report(where_: &str, die_if_leaks: bool) {
    assert_initialized_main_thread!();
    unsafe {
        ffi::gjs_memory_report(where_.to_glib_none().0, die_if_leaks.into_glib());
    }
}
